# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PqpL0f2AyOidCAPAJzubi51Pi0FJP0c
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Interactive Regression Lab", layout="wide")

st.title(" Regression ")
#st.write("A simple, visual, and beginner-friendly way to understand regression models.")

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("insurance.csv")
    return df

df = load_data()

st.subheader("🔍 Dataset Preview")
st.dataframe(df.head())

st.subheader("📏 Dataset Shape")
st.write(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")